# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Meet Rajyaguru
title: MEng, E.I.T.
email: meetjognesh.rajyagur@ucalgary.ca
#phone: +1(607)-262-0484
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  ad852
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: __m_e.e_t__
linkedin_username: meet-rajyaguru-b6666117a
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)
additional_links:
- title: Pdf Download
  icon: far fa-file-pdf
  url: https://github.com/meetrajyaguru98/meetrajyaguru98.github.io/blob/main/resources/Meet.CV.pdf
# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Meet picture.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Meet Rajyaguru and I am a highly motivated Chemical Engineering Professional with extensive hands-on knowledge of high-end industrial simulation software such as Aspen Plus, HYSYS, and Bluebeam RevU. I am a registered Engineer-in-Training (EIT) with the Association of Professional Engineers and Geoscientists of Alberta (APEGA) and currently working with the Facilities Engineering team at Strathcona Resources’ Tucker Thermal Facility. With a passion for learning and a deep commitment to my profession, I am dedicated to expanding my expertise and knowledge in the Canadian Oil and Gas industry, specifically as a Facilities Engineer. I am eager to work closely with industry professionals and apply my skills to tackle the most challenging engineering projects and contribute to the continued success of the industry.
content:
  - title: HIGHLIGHTS OF QUALIFICATIONS # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Key Strengths and Expertise
        # link_text: Project Website
        
        quote: >
          My unique blend of theoretical knowledge and practical expertise, combined with my commitment to professionalism and ethical conduct, allows me to provide effective solutions to complex engineering challenges in the Oil and Gas sector.
        description: | # this will include new lines to allow paragraphs
          As a Chemical Engineering Professional with experience in the Canadian Oil and Gas sector and a Master's degree from the University of Calgary, I bring a unique blend of theoretical knowledge and practical expertise to the table. With a strong foundation in plant troubleshooting and a track record of supporting successful Management of Change (MOC) initiatives, I am well-versed in the use of industrial simulation software, including IBM Maximo, Autodesk Navisworks, Bluebeam Revu, Aspen HYSYS, and MS Office. In addition, my prior work experience at Indian Oil Corporation Limited (IOCL) Refinery has given me valuable insights into engineering environments, further enhancing my skillset. As a registered Engineer-In-Training (EIT) with APEGA, I am committed to upholding the highest standards of professionalism and ethical conduct in all aspects of my work.
      
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Strathcona Resources Ltd.
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: On-Site Facilities Engineering Intern
        caption: September 2022 - Present
        quote: >
          Coupling technical expertise with project management skills and a safety-focused mindset, I strive to deliver high-quality work that meets stakeholder needs and exceeds expectations.
        description: | # this will include new lines to allow paragraphs
            As an accomplished Chemical Engineering Professional, I have extensive experience in preparing Engineering Work Packages and Construction Work Packages that span a wide range of scopes, from small replace-in-kind projects to large-scale Management of Change (MOC) initiatives that involve multiple departments and stakeholders. I have a keen eye for detail and excel at scoping projects, completing walk-downs, and managing the close-out process to ensure that all deliverables are completed on time and to the highest standards.

            One of my key strengths is my proficiency in P&ID redlining and mark-ups, as well as my ability to develop Engineering Drawings and Datasheets that accurately capture the technical requirements of a project. I have a deep understanding of the intricacies involved in these processes and can work effectively with cross-functional teams to ensure that all aspects of a project are thoroughly considered and accounted for.

            In addition to my technical expertise, I am skilled at facilitating touch-base meetings with Engineering, Operations, and Maintenance teams to discuss the status and progress of ongoing projects. These meetings are essential for keeping all stakeholders informed and engaged in the project, which is critical to ensuring successful project outcomes.

            As part of my work on MOC projects, I have also gained experience in facilitating Risk Assessments, participating in Process Hazards Analysis (PHA) and Pre-Startup Safety Reviews (PSSRs). These activities are essential for identifying potential hazards and mitigating risks associated with MOC projects, and I am adept at guiding cross-functional teams through these processes to ensure that all risks are identified and addressed.

            Finally, I played a key role in helping to complete an audit of over 200 car seals, which was critical to ensuring that overpressure protection was maintained on site. This experience gave me valuable insights into the importance of attention to detail and the need to maintain high levels of safety and compliance in all aspects of plant operations.

  
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Languages
        description: <img align="middle" src="images/Languages.jpg" alt="hi" class="inline"/>
      - layout: top-middle
        title: Libraries
        description: <img align="middle" src="images/Libraries.jpg" alt="hi" class="inline"/>  
      - layout: top-middle
        title: Frameworks
        description: <img align="middle" src="images/Frameworks.jpg" alt="hi" class="inline"/>
      
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cornell University
        caption: 2022 - 2023
        sub_title: MEng with concentration in Financial Engineering
        quote: >
          Cornell University is a prestigious Ivy League research institution located in Ithaca, New York. It offers a diverse range of undergraduate, graduate, and professional degree programs across multiple fields of study.
        description: | # this will include new lines to allow paragraphs
          During my time at Cornell I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. 
          
          <mark>GPA:</mark> 4
    
    #layout: list # Type of content section (list/text)
    #content:
      - layout: left
        title: BITS Pilani, Goa
        caption: 2016 - 2020
        sub_title: B.E. of Electrical and Electronics
        quote: >
          BITS Pilani Goa offers undergraduate and postgraduate degree programs in engineering, science, and management, and is renowned for its high-quality education and research facilities.
        description: | # this will include new lines to allow paragraphs
          During my time at BITS Pilani Goa, I was part of Department of Photography. I learned practical skills as well as had some of the best days of my academic at BITS. life 
          
          <mark>GPA:</mark> 8.56 / 10
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests and passion in financial markets and data anlytics some of my other interests and hobbies are:
      - Soccer
      - Health and Fitness
      - Anime
      - Manga

      Look at this cool image of my idol: 
      
      <img align="right" src="images/Ronaldo.jpg" alt="hi" class="inline"/>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
